// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"github.com/wisle25/be-template/applications/use_case"
	"github.com/wisle25/be-template/infrastructures/database"
	"github.com/wisle25/be-template/infrastructures/generator"
	"github.com/wisle25/be-template/infrastructures/repository"
	"github.com/wisle25/be-template/infrastructures/security"
	"github.com/wisle25/be-template/infrastructures/validation"
)

// Injectors from UserContainer.go:

func NewUserContainer() *use_case.UserUseCase {
	db := database.ProvideDB()
	idGenerator := generator.NewUUIDGenerator()
	userRepository := repository.NewUserRepositoryPG(db, idGenerator)
	passwordHash := security.NewArgon2()
	validate := validation.NewValidator()
	translator := validation.NewValidatorTranslator(validate)
	validateUser := validation.NewValidateUser(validate, translator)
	userUseCase := use_case.NewAddUserUseCase(userRepository, passwordHash, validateUser)
	return userUseCase
}
