// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"database/sql"
	"github.com/redis/go-redis/v9"
	"github.com/wisle25/be-template/applications/use_case"
	"github.com/wisle25/be-template/commons"
	"github.com/wisle25/be-template/infrastructures/cache"
	"github.com/wisle25/be-template/infrastructures/generator"
	"github.com/wisle25/be-template/infrastructures/repository"
	"github.com/wisle25/be-template/infrastructures/security"
	"github.com/wisle25/be-template/infrastructures/validation"
)

// Injectors from user_container.go:

func NewUserContainer(config *commons.Config, db *sql.DB, client *redis.Client) *use_case.UserUseCase {
	idGenerator := generator.NewUUIDGenerator()
	userRepository := repository.NewUserRepositoryPG(db, idGenerator)
	passwordHash := security.NewBcrypt()
	validate := validation.NewValidator()
	translator := validation.NewValidatorTranslator(validate)
	validateUser := validation.NewValidateUser(validate, translator)
	token := security.NewJwtToken(idGenerator)
	cache := cache.NewRedisCache(client)
	userUseCase := use_case.NewUserUseCase(userRepository, passwordHash, validateUser, config, token, cache)
	return userUseCase
}
